version: 1
from: "nfra/kickstart-flavor-jekyll"
ports: "80:80/tcp"

command:
  build:
  - "jekyll build -s /opt/docs -d /var/www/html"

  dev:
  - "D:jekyll build -s /opt/docs -d /var/www/html --watch --force_polling"

