version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.0"
ports: "80:80/tcp;4000:4000/tcp;4100:4100/tcp"

packages: ["php8.0-curl", "php8.0-http", "php8.0-raphf", "php8.0-xml"]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    ##- "sudo apt-get update && sudo apt-get install -y php-libsodium"
    - "composer update"

  test:
    - "phpunit"

