version: 1
from: "nfra/kickstart-flavor-php:7.4"

apache_document_root: "/opt/www"
apache_vhost_config: |
    FallbackResource /index.php
    php_admin_value file_uploads 0

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    ##- "sudo apt-get update && sudo apt-get install -y php-libsodium"
    - "composer update"

  test:
    - "phpunit"

